Date umane
Gruppo-TecWeb/Codice pull request #176
Opened 2024-04-15 15:09 UTC by rzaupa

Sistemarle in base al browser non so come si faccia, può andare anche così?

2024-04-19 15:25 UTC, LewentalDigital requested changes
Sarebbe meglio in formato esteso: 19 Aprile 2024
Molto più umano

2024-04-20 14:52 UTC, rzaupa commented
> Sarebbe meglio in formato esteso: 19 Aprile 2024 Molto più umano

in e6d402e2be69bf8da457bdebec3997dfcfd7315d ho inserito la formattazione delle date che dici te, in:
- index
- eventi (incluso il messaggio dei filtri)
- evento 

Peccato che a me vscode segnala che quella che ho usato (strftime) è una funziona deprecata , però al momento funziona, te che dici di fare? Andrebbe bene così?

2024-04-23 09:19 UTC, LewentalDigital commented
So che è una rottura di palle, ma la funzione deprecata non è ideale
Abbiamo provato con Antonio a usare IntlDateFormatter, ma è un casino da importare

Sto pensando che la soluzione ideale sia di avere un array con i 12 mesi in italiano e usarlo per crearsi la data come vogliamo
Dimmi se è troppo un'eresia @rzaupa

2024-04-23 09:23 UTC, rzaupa commented
@LewentalDigital mi hai appena proposto quello che mi avete fatto togliere senza pensarci mesi fa con la funzione di formattazione delle date...

2024-04-23 10:06 UTC, LewentalDigital commented
> @LewentalDigital mi hai appena proposto quello che mi avete fatto togliere senza pensarci mesi fa con la funzione di formattazione delle date...

![image](https://github.com/Gruppo-TecWeb/Codice/assets/151509931/2bb7063f-41c4-422c-9920-a0875bb83eab)

loool

In effetti è vero, ma non sapevamo che non avrebbe funzionato la funzione nativa fino ad ora, comunque a questo punto se si riesce, usiamo la nostra funzione (che hai già preparato mesi fa), sennò al limite formattiamo le date GG/MM/AAAA con la funzione nativa

2024-05-06 21:36 UTC, rzaupa commented
In [0fdce26](https://github.com/Gruppo-TecWeb/Codice/pull/176/commits/0fdce2688fc91df8d71480518b70711951f46169) reinserita la famosa funzione non nativa tolta in fase preliminare senza giustificazioni e senza portare un'alternativa valida. Può andare bene ora @LewentalDigital ?

2024-05-13 22:02 UTC, LewentalDigital approved these changes
Perfetto, ottimo lavoro e rimarcabile pazienza

2024-05-13 22:07 UTC, LewentalDigital commented
Solo una domanda: è ancora necessario avere: 
setlocale(LC_TIME, 'it_IT', 'it', 'IT', 'italian');
?

2024-05-16 09:19 UTC, merged