Feature/aggiornamento classifiche
Gruppo-TecWeb/Codice pull request #194
Opened 2024-05-06 21:09 UTC by abenetazzo

Probabilmente in parte risolve issue #121

2024-05-07 08:43 UTC, abenetazzo commented
ho aggiunto nello stesso branch un fix per un bug che ho trovato nella pagina classifiche, ho anche migliorato la pagina gestione-classifiche dell'area admin

2024-05-09 15:25 UTC, LewentalDigital requested changes
Cambiare immagini fungo nuove

2024-05-30 11:23 UTC, abenetazzo commented
creata issue a parte

2024-05-30 11:24 UTC, LewentalDigital approved these changes

2024-05-30 11:24 UTC, merged