Ripresa vecchie modalità
Gruppo-TecWeb/Codice pull request #210
Opened 2024-05-23 17:00 UTC by T-Brex

Ripristino versione di Modalità con iframe

Risolte issue:

#208 
#197 (anche per  la pagina beats)
#165 
#162(chiusa per cambio strategia)
#134(il bottone è rimasto un bottone, vabbene @LewentalDigital ?)
#73(youtube ha i sottotitoli, bastano @rzaupa ?)

2024-05-28 07:24 UTC, LewentalDigital requested changes
- [x] Togliere lo script delle API di youtube dal template di pagina e metterlo all'inizio o alla fine di modalita.html
- [x] Togliere gli audio per ogni beat, in teoria non sono più necessari


> #134(il bottone è rimasto un bottone, vabbene LewentalDigital ?)

No, o almeno no come è ora, scrivo più info nella issue originaria; risolvere in un'altra pull request

2024-05-30 10:40 UTC, abenetazzo approved these changes

2024-05-30 10:49 UTC, abenetazzo approved these changes

2024-05-30 10:53 UTC, LewentalDigital approved these changes

2024-05-30 10:53 UTC, merged