Feature/video
Gruppo-TecWeb/Codice pull request #224
Opened 2024-05-30 18:14 UTC by LewentalDigital

implementato video più accessibile possibile
per favore durante la verifica valutare il più possibile l'accessibilità

closes #164

2024-05-30 18:19 UTC, LewentalDigital commented
il formattatore css ha formattato anche le cose di bre, per quello mostra un sacco di diff

2024-06-01 08:57 UTC, abenetazzo commented
Credo ci siano un paio di problemi...

- i sottotitoli vengono tagliati, ma credo il vero problema sia il fatto che la finestra del video non mostra tutta la larghezza
![Schermata 2024-06-01 alle 10 52 02](https://github.com/Gruppo-TecWeb/Codice/assets/79547694/e51b399b-0a2e-475d-8992-7a71a4ccd30d)

- il video in altezza non si limita al riquadro dove dovrebbe stare (che tra l'altro non è allineato correttamente) ma va anche più in basso, sotto l'immagine del fungo
![Schermata 2024-06-01 alle 10 52 17](https://github.com/Gruppo-TecWeb/Codice/assets/79547694/a7dcf906-9894-47de-888d-009a869d038c)

Poi se non erro avevamo detto di mettere i sottotitoli disattivati di default, non ci sei riuscito?

2024-06-01 09:18 UTC, abenetazzo requested changes
vedi commento precedente

2024-06-02 07:50 UTC, abenetazzo approved these changes
Per me va bene, non chiudo la pr per dare la possibilità anche a rich di controllare e dire la sua.

2024-06-03 21:51 UTC, LewentalDigital commented
Trovato il modo di non mostrare i sottotitoli di default!
Basta togliere l'attributo "default" sul tag track (chi lo avrebbe mai detto?)

Comunque io per la consegna quasi quasi li metterei di default, boh, decideremo

2024-06-03 21:51 UTC, merged