Feature/138 rimuovere titoli
Gruppo-TecWeb/Codice pull request #225
Opened 2024-06-01 08:36 UTC by abenetazzo

closing #138

2024-06-03 21:43 UTC, LewentalDigital requested changes
Perfetto il filtro con tipo evento

Possiamo aggiungere qui la funzione che quando non ci sono eventi futuri/corrispondenti ai filtri, e mostra il link per vedere quelli passati, **cliccando il link mantiene il filtro impostato**, che ne dici?

Si tratta di aggiungere un tag di come {filtroEvento} al link che viene rimpiazzato con quello settato nel get

Esemio Eventi.html-Linea 48
`<p class="eventiMessaggio limitedWidth">{messaggio}, sfoglia i nostri <a href="eventi.php?data={dataEventiPassati}&tipoEvento={filtroEventi}">eventi passati</a></p>`

2024-06-03 22:10 UTC, abenetazzo commented
> Perfetto il filtro con tipo evento
> 
> Possiamo aggiungere qui la funzione che quando non ci sono eventi futuri/corrispondenti ai filtri, e mostra il link per vedere quelli passati, **cliccando il link mantiene il filtro impostato**, che ne dici?
> 
> Si tratta di aggiungere un tag di come {filtroEvento} al link che viene rimpiazzato con quello settato nel get
> 
> Esemio Eventi.html-Linea 48 `<p class="eventiMessaggio limitedWidth">{messaggio}, sfoglia i nostri <a href="eventi.php?data={dataEventiPassati}&tipoEvento={filtroEventi}">eventi passati</a></p>`

Si può fare, mi vengono in mente anche un altro paio di cose:
- [ ] aggiungerei anche che il link per vedere gli eventi passati (senza filtri, quindi come quello che c'è attualmente) sia sempre visibile, in modo da poter sempre vedere gli eventi passati;
- [ ] quando vengono visualizzati gli eventi passati li ordinerei in ordine cronologico inverso, ovvero dal più recente al più vecchio;
- [ ] se non è troppo complicato, si potrebbe anche aggiungere un campo per poter decidere l'ordinamento degli eventi.

2024-06-03 22:18 UTC, LewentalDigital commented
Buone idee, richiedono di pensare bene il loro posizionamento e il design per un facile utilizzo
Sì, apro una issue separata post progetto

Domani implementiamo assieme questo che è ez e chiudiamo la PR:

> Possiamo aggiungere qui la funzione che quando non ci sono eventi futuri/corrispondenti ai filtri, e mostra il link per vedere quelli passati, cliccando il link mantiene il filtro impostato, che ne dici?

2024-06-06 14:02 UTC, LewentalDigital approved these changes

2024-06-06 15:59 UTC, merged