Feature/188 design evento no immagine
Gruppo-TecWeb/Codice pull request #238
Opened 2024-06-05 12:24 UTC by LewentalDigital

## Lista eventi con design evento senza img
## Pagina evento con design evento senza img

closes #188

2024-06-08 23:20 UTC, LewentalDigital commented
Un trucco che l'utilizzo del css inline permetteva era la possibilità di dare rotazioni casuali al testo decorativo degli eventi senza immagine, se lo credete figo, valutate di ammettere il css inline
![image](https://github.com/Gruppo-TecWeb/Codice/assets/151509931/e9785c9f-f298-4390-b3ff-7834ce064944)

2024-06-08 23:23 UTC, LewentalDigital commented
Unica pecca, non riesco proprio a risolvere questo spazio nero nei titoli degli eventi senza immagini
![image](https://github.com/Gruppo-TecWeb/Codice/assets/151509931/d347fb67-01cc-4aed-8daf-e25979e6842f)

Uffa

2024-06-09 08:29 UTC, rzaupa requested changes
Dalle immagini che mostri sembra carino ma purtroppo non vedo le tue modifiche nel branch, ma vedo robe strane :(
<img width="467" alt="Screenshot 2024-06-09 102849" src="https://github.com/Gruppo-TecWeb/Codice/assets/126966421/e636a457-0be4-4fa3-b0e0-3bbbf13f15ab">
Solo io ? (xxxxxxxxx)
Comunque per il fix in line difficile fare trattative , la gaggi lo becca subito con gli strumenti tipo Total validator

2024-06-09 09:57 UTC, LewentalDigital commented
@rzaupa hai provato a ricaricare il css? Magari hai ancora in cache quello precedente 

Shift + F5

2024-06-09 14:55 UTC, abenetazzo commented
> Dalle immagini che mostri sembra carino ma purtroppo non vedo le tue modifiche nel branch, ma vedo robe strane :( <img alt="Screenshot 2024-06-09 102849" width="467" src="https://private-user-images.githubusercontent.com/126966421/337958695-e636a457-0be4-4fa3-b0e0-3bbbf13f15ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NDQ4NzksIm5iZiI6MTcxNzk0NDU3OSwicGF0aCI6Ii8xMjY5NjY0MjEvMzM3OTU4Njk1LWU2MzZhNDU3LTBiZTQtNGZhMy1iMGUwLTNiYmJmMTNmMTVhYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQxNDQ5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTdkOWE5MGM5OTkyOGMzMDkyNDA0NDFkN2E3M2VjN2M5ZjEzMTA4YTM1NjhmN2FjMjE0MmQwYzg2ZTE4OTc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.BpVVoBlk3C1x8nENPbx2_bpkmuvXBz7yvZZ21eSJ0xE"> Solo io ? (xxxxxxxxx) Comunque per il css in line difficile fare trattative , la gaggi lo becca subito con gli strumenti tipo Total validator

Se non erro era un problema che avevamo già risolto, credo basti fare un merge dal develop per risolverlo. Inoltre @LewentalDigital ci sono dei conflitti, anche questi li puoi risolvere con un merge dal develop, a sto punto direi che sia meglio fare sto merge per poi valutare.

2024-06-09 15:00 UTC, rzaupa reviewed
Ora in effetti mi esce 
<img width="161" alt="Screenshot 2024-06-09 165504" src="https://github.com/Gruppo-TecWeb/Codice/assets/126966421/99615f38-85e4-458f-b29e-b6db0bfc9b47">
che deduco che sia il risultato atteso...
Ho provato ad inserire un nuovo evento e non c'è il problema dello spazio tra l'immagine e il titolo e il titolo e la data... boh, quindi va bene ? non saprei
<img width="166" alt="Screenshot 2024-06-09 165734" src="https://github.com/Gruppo-TecWeb/Codice/assets/126966421/4810b715-1c1a-4db0-b319-e66c125f4d9a">
Unica cosa mi lascia un po' perplesso il redesign della pagina evento. Poco adattiva rispetto allo schermo, guarda
<img width="1267" alt="Screenshot 2024-06-09 165956" src="https://github.com/Gruppo-TecWeb/Codice/assets/126966421/434cb72b-967a-45ef-80e6-343d69f7b3ef">

è un po' skill issue, che ne pensi ?

2024-06-09 16:30 UTC, LewentalDigital commented
Ho migliorato la situazione, grazie per avermelo fatto notare!

2024-06-09 16:45 UTC, rzaupa requested changes
Situazione decisamente migliorata ma manca un dettaglio, per gli eventi senza classifiche (indipendentemente dallo schermo, tranne da mobile) esce così: 
<img width="933" alt="Screenshot 2024-06-09 184355" src="https://github.com/Gruppo-TecWeb/Codice/assets/126966421/85effd3a-0d5e-4821-87d1-41c512afb244">
Cioè uno spazio esagerato tra il titolo e le info dell'evento, riesci a fixare ?

2024-06-09 16:51 UTC, LewentalDigital commented
Ci sto provando, ma è bello difficile, non so se ci riuscirò

2024-06-12 22:36 UTC, LewentalDigital commented
Non sono in grado di risolvere quella cosa attualmente
Skill issue direi :(


Puoi approvarla in questo stato e ci penseremo più in la?

2024-06-13 07:32 UTC, rzaupa commented
> Non sono in grado di risolvere quella cosa attualmente Skill issue direi :(
> 
> Puoi approvarla in questo stato e ci penseremo più in la?

Però approvarla vorrebbe dire mettere nel sito qualcosa di "rotto" e se poi non riusciamo a sistemare ( anche perché abbiamo poco tempo )? sarebbe meglio farlo qui anche perché la pull request si riferisce proprio a questi cambiamenti... o no ? Al massimo ci pensiamo più in là in questo branch... dimmi se hai qualcosa in contrario o avevi altre idee

2024-06-13 08:14 UTC, abenetazzo commented
Da quel che vedo il problema è la definizione della griglia, in particolare la proprietà grid-template-rows (vedi screenshot). 
![Schermata 2024-06-13 alle 10 12 09](https://github.com/Gruppo-TecWeb/Codice/assets/79547694/69e2d984-5613-4e5a-841d-c30d8035d8de)

Come mai hai voluto mettere il link indietro e il titolo con due altezze diverse? Se non erro è quello che ti costringe a creare una terza riga ed è la dimensione di questa che crea il problema...

2024-06-13 15:25 UTC, LewentalDigital commented
Ok ho trovato il modo di ripararlo

2024-06-13 15:31 UTC, rzaupa approved these changes
Mi sembra tutto a posto, ottimo lavoro

2024-06-13 15:45 UTC, merged