risoluzione #248(e #249) e modifiche css
Gruppo-TecWeb/Codice pull request #252
Opened 2024-06-07 11:12 UTC by T-Brex

per quanto riguarda la #249 io la vedo sia nel mio branch sia nel develop

2024-06-08 08:46 UTC, abenetazzo commented
Ci sono dei conflitti, li risolvi tu @T-Brex ?

2024-06-10 12:52 UTC, T-Brex commented
@abenetazzo @rzaupa @LewentalDigital  qualcuno mi approva la pull?

2024-06-10 15:19 UTC, rzaupa requested changes
Per modalità total validator mi segnala solo:
<img width="600" alt="Screenshot 2024-06-10 171158" src="https://github.com/Gruppo-TecWeb/Codice/assets/126966421/42dd1625-469f-4e71-b970-6e8d7c50161b">
ed in effetti è un link che non va 

Per beats la faccenda è un po' piu' complicata, forse meglio discuterne in una issue a parte appunto. Il validatore non è contento.


ARC Toolkit per modalità mi continua a segnaalre:
<img width="430" alt="Screenshot 2024-06-10 171812" src="https://github.com/Gruppo-TecWeb/Codice/assets/126966421/563de271-f73c-49ae-a985-7d9c95388c3a">

2024-06-10 16:58 UTC, rzaupa approved these changes
Ho fatto i test con :
- total validator
- html checker
- arc toolkit

non ci sono errori, ottimo

2024-06-10 17:26 UTC, merged