fix/267-total-validator-gestione-eventi
Gruppo-TecWeb/Codice pull request #274
Opened 2024-06-08 18:40 UTC by abenetazzo

Ho reso univoci i name dei button.

2024-06-08 18:59 UTC, rzaupa requested changes
Si intendeva eventi.php nell'area admin

2024-06-08 21:26 UTC, abenetazzo commented
Appunto... i file modificati sono:
- admin/gestione-eventi.php
- template/admin/eventi.html
entrambi relativi all'area admin.

2024-06-09 08:10 UTC, rzaupa requested changes
Ho visto i file modificati e per questo ho detto. L'errore segnalato è in Admin/eventi.php non in gestione-eventi.php. Se si sono risolti errori in gestione-eventi.php meglio ma non basta per poter chiudere la issue #267

2024-06-09 15:04 UTC, abenetazzo commented
L'errore, come hai segnalato tu, è dovuto al fatto che il valore dell'attributo name dei button (nello specifico si parla dei button modifica, punteggi ed elimina) nei vari form (uno per ogni riga) non era univoco. Per renderlo univoco l'ho modificato (quindi ho cambiato il file template/admin/eventi.html).

Per risolvere la issue sarebbe quindi bastata questa modifica. Peccato che il valore dell'attributo name di quei button siano anche valori utilizzati dal codice php che riceve in input questi dati, quindi in questo caso stiamo parlando della pagina admin/gestione-eventi.php, destinazione dei form presenti nella pagina admin/eventi.php; non mi sembrava una scelta saggia quella di lasciare una pagina non funzionante, ecco spiegato il perché ho modificato anche il file admin/gestione-eventi.php.

Non capisco quale sia il problema...

2024-06-09 15:10 UTC, rzaupa reviewed
Il problema sta semplicemente nel fatto che i problemi segnalati nella issue #267  non si sono risolti, al massimo se ne sono generati altri....
<img width="786" alt="Screenshot 2024-06-09 170839" src="https://github.com/Gruppo-TecWeb/Codice/assets/126966421/41f7fbbe-0514-450e-a228-ec1f41528b6d">

2024-06-09 15:16 UTC, abenetazzo commented
Allora credo di aver male interpretato il problema... Io avevo capito che il problema stesse nel fatto che il valore dell'attributo name di un button (più in generale il valore di tutti gli attributi name) dovesse essere univoco, come per gli id. Se invece si riferisce al testo che sta dentro il tag button, quindi il testo visualizzato nel button, allora il problema è diverso e non avrei idea di come risolverlo...

2024-06-09 15:19 UTC, abenetazzo commented
Forse si risolve aggiungendo un attributo aria-label con una descrizione dettagliata per gli screen reader, almeno così sto trovando online... che ne pensi?

2024-06-09 15:35 UTC, abenetazzo commented
Sono tornato alla versione precedente, ora l'unica modifica rispetto al develop è la presenza degli attributi aria-label, prova a vedere se con questi i problemi compaiono ancora o sono risolti. Se va bene così faccio la stessa cosa anche per le altre pagine.

2024-06-09 15:39 UTC, rzaupa requested changes
Ancora niente...
<img width="772" alt="Screenshot 2024-06-09 173841" src="https://github.com/Gruppo-TecWeb/Codice/assets/126966421/4fd8ba3a-337b-4ec0-afbb-7cadb524ef40">
_Use unique labels so that users can distinguish between form controls on the same page when read out aloud. Alternatively, place them within different <fieldset> with unique <legend> labels, because the legend text is read out along with the label text. See [WCAG2 Success Criterion 2.4.6](https://www.w3.org/TR/WCAG22/#headings-and-labels)._

2024-06-09 16:14 UTC, abenetazzo commented
Ho provato un'altra soluzione, anche se non mi fa impazzire... Altrimenti non saprei cos'altro fare.

2024-06-09 16:16 UTC, rzaupa approved these changes
Confermo che gli errori non ci sono, soluzione un po' così, se ci ripensi richiedi la rieview. Al momento approvo

2024-06-09 16:24 UTC, abenetazzo commented
Io intanto mergio e applico la stessa soluzione anche nelle altre pagine, magari vediamo con calma in futuro come migliorarla.

2024-06-09 16:24 UTC, merged