resi univoci i name dei button
Gruppo-TecWeb/Codice pull request #276
Opened 2024-06-08 18:49 UTC by abenetazzo

Ho reso univoci i name dei button.

2024-06-08 18:59 UTC, rzaupa requested changes
Si intendeva classifiche php nell'area admin

2024-06-08 21:28 UTC, abenetazzo commented
Appunto... i file modificati sono:
- admin/gestione-classifiche.php
- template/admin/classifiche.html
entrambi relativi all'area admin.

2024-06-09 08:15 UTC, rzaupa submitted a review, later dismissed

2024-06-09 08:17 UTC, rzaupa requested changes
Gli errori rimangono, sistemare classifiche.php

2024-06-09 16:29 UTC, abenetazzo commented
Applicata nuova soluzione, fammi sapere come va.

2024-06-09 16:35 UTC, rzaupa approved these changes
Confermo che sono stati eliminati gli errori

2024-06-09 16:35 UTC, merged