Fix/293 campi obbligatori form
Gruppo-TecWeb/Codice pull request #298
Opened 2024-06-10 20:51 UTC by abenetazzo

Ho aggiunto le indicazioni per i campi obbligatori nei vari form, mettendo anche indicazioni accessibili per gli screen reader.
Ho anche aggiunto lato client tutti i controlli, in modo che l'utente abbia riscontro immediato sull'input inserito e impedisce l'invio del form se l'input inserito non rispetta le indicazioni.

Non è stato un lavoro semplice, credo di aver sistemato tutto, fammi sapere se c'è ancora qualcosa che non va.

2024-06-13 09:02 UTC, rzaupa commented
https://web.math.unipd.it/accessibility/dettaglio.html?ID=68
Gli errori devono essere visualizzati in modo visuale usando il colore, qui non lo si utilizza

https://web.math.unipd.it/accessibility/dettaglio.html?ID=72
I campi obbligatori idem : servono colore e aria-required oltre che asterisco

2024-06-13 09:22 UTC, abenetazzo commented
> https://web.math.unipd.it/accessibility/dettaglio.html?ID=68 Gli errori devono essere visualizzati in modo visuale usando il colore, qui non lo si utilizza

Mmmm... L'idea di usare il colore non mi fa impazzire ma ci può stare, poi se è obbligatorio non abbiamo molta scelta.

> https://web.math.unipd.it/accessibility/dettaglio.html?ID=72 I campi obbligatori idem : servono colore e aria-required oltre che asterisco

Gli attributi aria-required dovrebbero esserci già.

Visto che sia qua che nella pr #306 sto lavorando sull'area admin e sicuramente ci saranno conflitti, prima di andare avanti direi di chiudere l'altra pr, così mergiamo, risolvo i conflitti e lavoro una volta sola.

2024-06-13 21:11 UTC, abenetazzo commented
Ok, ho rivisto un po' di cose, prova a darci un'occhiata e fammi sapere.

2024-06-14 11:37 UTC, LewentalDigital commented
Ho notato una cosa: in un caso con piu' messaggi come eventi.php?errore=true&eliminato=true 
Prima venivano mostrati i 2 messaggi
Ora si vede solo 1: 'Evento eliminato correttamente'

E' comportamento normale?

2024-06-14 11:49 UTC, LewentalDigital requested changes
C'e' un problema sulla modifica di Rapper, Admin, TipoEvento:
Da dentro la pagina di modifica se modifico il informazioni, mi dice 'Email già registrata.' o 'Esiste già un tipo evento con questo titolo ' o cose simili, probabilmente fa lo stesso controllo che viene eseguito nella registrazione di una nuova entry.

2024-06-14 11:55 UTC, LewentalDigital commented on styles/style.css
> +    color: green;
```suggestion
    color: lime;
```

2024-06-14 11:58 UTC, LewentalDigital commented
C'e' inoltre il problema dell'evento nella dashboard senza immagine
Il layout vecchio non fa il controlle se la locandina e' null allora mete l'immagine rotta

Potremmo semplicemente fare il controllino e tolgiere l'immmagine direttamente se non c'e', al posto di importare il nuovo layout che comportertebbe molto lavoro

2024-06-14 12:39 UTC, LewentalDigital commented
Una cosa semplice da risolvere e' il design dei form di modifica da mobile che hanno overflow:
![image](https://github.com/Gruppo-TecWeb/Codice/assets/151509931/4978a549-9948-45b9-9c2b-59bbcb9eead7)

basta modificare il template della grid di **#login form, .adminPage form.aggiunta-modifica** in questo modo:

```
grid-template-areas:
        'titolo'
        'messaggi'
        'input'
        'bottoni';

```

2024-06-14 13:37 UTC, abenetazzo commented
> Ho notato una cosa: in un caso con piu' messaggi come eventi.php?errore=true&eliminato=true Prima venivano mostrati i 2 messaggi Ora si vede solo 1: 'Evento eliminato correttamente'
> 
> E' comportamento normale?

Sì, è un comportamento normale, nel senso che se c'è un errore non può dire che un'operazione è stata fatta correttamente. Però in effetti in questo caso sarebbe meglio mostrare il messaggio di errore e non la conferma, quindi modifico.

2024-06-14 15:49 UTC, abenetazzo commented
Ho risolto tutto tranne, in parte, questo (altro che semplice!!!)...

> Una cosa semplice da risolvere e' il design dei form di modifica da mobile che hanno overflow:
> basta modificare il template della grid di **#login form, .adminPage form.aggiunta-modifica** in questo modo:
> 
> ```
> grid-template-areas:
>         'titolo'
>         'messaggi'
>         'input'
>         'bottoni';
> ```

Ho fatto come hai detto tu ed in effetti sembra praticamente risolto... solo che in funzione di quale smartphone si simuli, e quindi delle diverse dimensioni dello schermo, il margine destro si sminchia... Immagino non dipenda da questa grid, ma andrebbe analizzato il motivo e risolto. Ho provato ad impostare una max-width usando la var --widthMenu ma non fa alcun effetto, solo impostando un margin-right si ha un effetto, ma che appunto cambia in base alla dimensione dello schermo.

![Schermata 2024-06-14 alle 17 44 52](https://github.com/Gruppo-TecWeb/Codice/assets/79547694/9df4864b-6dfe-477c-9282-c552a7e005c2)

![Schermata 2024-06-14 alle 17 45 09](https://github.com/Gruppo-TecWeb/Codice/assets/79547694/1418ebb6-910b-4b05-983e-d7527794a6d0)

![Schermata 2024-06-14 alle 17 45 19](https://github.com/Gruppo-TecWeb/Codice/assets/79547694/24933259-8e5a-4cb9-973e-c7c5c539857a)

2024-06-15 12:59 UTC, LewentalDigital commented
Hai caricato la tua immagine di profilo come foto profilo admin, a me va anche bene hahaha 
Era inteso?

2024-06-15 13:06 UTC, abenetazzo commented
> Hai caricato la tua immagine di profilo come foto profilo admin, a me va anche bene hahaha Era inteso?

No, non era voluto ahahaha.
Refuso di qualche test.

2024-06-15 13:08 UTC, LewentalDigital commented
Se vogliamo tenerla aggiorna anche il DB in modo che venga mostrata
Decidi te se tenerla

2024-06-15 13:08 UTC, abenetazzo commented
Immagine rimossa...
Quindi @LewentalDigital approvi?

@rzaupa hai dato un'occhiata anche tu? Approvi?

2024-06-15 13:18 UTC, LewentalDigital commented
Ho trovato il colpevole dell'overflow:
la div dei bottoni
```
#login form div#buttons, .adminPage form.aggiunta-modifica div#buttons {
    grid-area: bottoni;
    display: flex;
    padding: 1em;
    align-items: center;
    justify-content: space-between;
    width: fit-content;
}
```
Per risolverlo si può aggiungere una regola da mobile in cui viene unsettato il display flex (che forzava la vistualizzazione in riga allungando la dimensione del sito).
Puoi rimuovere la regola max-width.
Suggerisco poi di togliere anche il padding del div dei bottoni e dell'h3 da mobile.
```
#login form div#buttons, .adminPage form.aggiunta-modifica div#buttons {
    display: unset;
    padding: unset;
}
```

2024-06-15 13:33 UTC, LewentalDigital commented
Un'ultima cosa già che ci sei:
puoi aggiungere una regola css mobile per il padding top delle pagine admin:
```
.adminPage {
    padding-top: 3.5em;
}
```
Dopo questi cambiamenti approvo e vorrei che @rzaupa la approvasse così da vaidare l'accessibilità.

2024-06-15 17:29 UTC, abenetazzo commented
Modifiche suggerite da @LewentalDigital apportate, se per te va bene metti la tua review.

In ogni caso per il merge attendiamo la review anche da parte di @rzaupa

2024-06-15 18:59 UTC, rzaupa approved these changes
Lavoro importante, ho verificato manualmente i test segnalati nella issue (sono il test 16, 70, 72 e 73 di https://web.math.unipd.it/accessibility/test.html) per ogni form e direi che sono passati. 

Se non sbaglio i campi che necessitano di errori sono:
- email
- numero nei punteggi 
domando se mi è sfuggito qualcosa

Avevo solo dei dubbi minori (dettagli che si possono tranquillamente ignorare)
- secondo voi è abbastanza esplicativo mettere "Email non valida" invece di mettere perchè non è valida (manca "@" oppure "è già presente nel db" )?
- non sono sicuro al 100% dei tasti di conferma e annulla in alto, comunque non era oggetto della issue e non ho trovato test che dicono il contrario quindi ok volevo un vostro parere
- il bottone "elimina" nel form non è ripetitivo con la pagina precedente ? Cioè forse pensavo che al form sarebbe meglio avere solo "Annulla" o "Conferma"
- ho notato che in gestione punteggi il form consente di confermare se non si è inserito nulla 
- per il form di gestione punteggi non si fa un controllo come lo si fa per le altre pagine quando si inserisce ad esempio una lettera, questo non viene segnalato subito lato client
- tipo quando ti esce il messaggio dopo "conferma" inserendo una mail sbagliata ad esempio, il messaggio rimane bloccato nella pagina se scorri (ripeto, dettagli da niente)
- ARC toolkit segnala qualcosina che non comprendo molto ma non era scopo della issue

2024-06-16 10:19 UTC, LewentalDigital approved these changes

2024-06-16 20:31 UTC, abenetazzo commented
> Se non sbaglio i campi che necessitano di errori sono:
> 
> * email
> * numero nei punteggi
>   domando se mi è sfuggito qualcosa
> 

oltre a questi in realtà vengono anche controllati:

- univocità degli username (nei form di rappers e amministratori)
- univocità dei titoli di classifica e tipo-evento
- campi obbligatori (in tutti i form)

> * secondo voi è abbastanza esplicativo mettere "Email non valida" invece di mettere perchè non è valida (manca "@" oppure "è già presente nel db" )?

Secondo me andare a dire che non è valida perchè manca la @ o il . credo sarebbe forse troppo... Per mia esperienza personale nei siti dove ho riscontrato un controllo sulla validità della mail non ho mai trovato la specifica del perchè non fosse valida. Magari possiamo rendere più esplicito il messaggio dicendo qualcosa del tipo "La mail dev'essere composta in questo modo ..." oppure "La mail deve avere questa forma ...".

> * non sono sicuro al 100% dei tasti di conferma e annulla in alto, comunque non era oggetto della issue e non ho trovato test che dicono il contrario quindi ok volevo un vostro parere

Era un dubbio che avevo anche io e su cui mi sono confrontato con @LewentalDigital .
Inizialmente li avevo messi in alto per uniformità con le altre pagine, poi su suo suggerimento ho modificato in modo che l'html riportasse i buttons dopo il form (così gli screen reader li leggono dopo) e tramite le grid venissero visualizzati in alto, ma in form più lunghi o anche da mobile in effetti uno che inserisce i dati deve poi tornare in alto per confermare, quindi non mi convince... Si potrebbero duplicare i buttons sia sopra che sotto (e magari var vedere solo quelli sotto agli screen reader), oppure seba proponeva i buttons attaccati al menù in modo che siano sempre visibili, magari lo rivediamo domani in un'altra issue.

> * il bottone "elimina" nel form non è ripetitivo con la pagina precedente ? Cioè forse pensavo che al form sarebbe meglio avere solo "Annulla" o "Conferma"

Sì, è ripetitivo, ma credo sia utile. Ci trovate qualcosa in contrario?

> * ho notato che in gestione punteggi il form consente di confermare se non si è inserito nulla
> * per il form di gestione punteggi non si fa un controllo come lo si fa per le altre pagine quando si inserisce ad esempio una lettera, questo non viene segnalato subito lato client

Qui non avevo trovato un motivo per impedire l'invio del form se non si è inserito nulla, non mi sembra formalmente scorretto. Per quanto riguarda i controlli non mi sembrava ce ne fossero di utili. Ho provato a digitare lettere o altro nei vari campi, ma a me il browser non me li fa inserire (credo dipenda dal type di input), a te li fa inserire?
In ogni caso in generale non mi fa impazzire questo form, lo trovo abbastanza scomodo... post consegna avevo in mente di rivederlo.

> * tipo quando ti esce il messaggio dopo "conferma" inserendo una mail sbagliata ad esempio, il messaggio rimane bloccato nella pagina se scorri (ripeto, dettagli da niente)

Sinceramente non ho capito qui cosa intendi dire... Magari domani me lo fai vedere.

> * ARC toolkit segnala qualcosina che non comprendo molto ma non era scopo della issue

Ok, in caso vediamo anche questo domani.



Direi che posso procedere a chiudere la pr, eventuali altre modifiche necessarie le vediamo domani o in altre issue.

2024-06-16 20:31 UTC, merged