Feature/206 design beats
Gruppo-TecWeb/Codice pull request #310
Opened 2024-06-13 20:33 UTC by LewentalDigital

# Piccolo redesign beats

- Cambiata posizione bottone descrizione
- Migliorato stile bottone descrizione
- Migliorato toggle bottone riproduzione automatica
- Migliorato player audio
- Fattorizzato codice html beats

closes #206

2024-06-13 22:11 UTC, abenetazzo commented
Secondo me si nota poco la differenza tra "riproduzione automatica" attiva e non attiva. Alla fine l'unica differenza è solo un puntino... perchè non lasciarlo coi colori invertiti quando è attivo, come quando c'è l'hover? Oppure mettere una sorta di interruttore on/off.

2024-06-14 09:26 UTC, T-Brex requested changes
Come dice antonio, non mi piace la distinzione della riproduzione automatica attiva e non attiva, io propongo di lasciare il colore invertito nel caso sia attivo, come facciamo per "audio descrizione", anche perchè credo che sia meglio dare un solo modo di vedere se una cosa è attiva o no, non ha senso "inventarsi" un nuovo modo per visualizzare ciò.
è un pò come se ci fossero due colori diversi per i link visitati, uno poi non sa benissimo come interpretare la cosa!

2024-06-14 10:29 UTC, LewentalDigital commented
Ok, ho applicato il vostro suggerimento 
Ho tenuto anche il pallino perché aiuta a capire il cambio di stato anche quando si ha l'hover sul bottone

2024-06-14 13:15 UTC, T-Brex approved these changes

2024-06-14 13:17 UTC, merged