Bre/issue302
Gruppo-TecWeb/Codice pull request #318
Opened 2024-06-17 10:20 UTC by T-Brex

- Modifiche a **btnDesc**

1. Aggiunta aria-expanded;
2. Ora il pulsante e' usabile anche dai non vedenti : la descrizione e' visibile solo se il bottone e' cliccato
3. Ordine lettura screen reader di un Beat:

1. nome del beat
2. tasto play/stop
3. tasto Audio descrizione
4. durata beat
5. descrizione beat
6. Jump al player audio

2024-06-17 16:23 UTC, LewentalDigital requested changes
implementare aria-controls che si riferisce alla descrizione beat che sta controllando
Usare l'attributo hidden per nascondere la descrizione al posto di aria-hidden

2024-06-18 12:57 UTC, LewentalDigital requested changes
Ci sono vari errorini
Riporto da linea 658:
```
<button class="btnDesc" aria-expanded="false">
    <span>Audio descrizione</span
    ><span class="navigationHelp">Tecniche Perfette - 5</span>
    ><span lang="en" class="navigationHelp">Tecniche Perfette - 5</span>
</button>
```
Vedo molti '>' e '<'  sbagliati sparsi in giro, e in questo caso vedo il lang en ma con un testo italiano

2024-06-18 13:12 UTC, T-Brex commented
> Vedo molti '>' e '<' sbagliati sparsi in giro, e in questo caso vedo il lang en ma con un testo italiano

sono corretti, è solo "prettier" che indenta in questo modo un pò folle, prova a fare una prova con i vari validatori, io ho provato con tatal validator, ma non da problemi

quel lang mi è scappato invece, correggo subito

2024-06-18 15:53 UTC, LewentalDigital commented
Sembre nel beat 18 Tecniche Perfette 5, il titolo h3 riporta il lang en

2024-06-19 08:30 UTC, LewentalDigital approved these changes
Ok, buon lavoro

2024-06-19 08:30 UTC, merged