Bre/issue327
Gruppo-TecWeb/Codice pull request #334
Opened 2024-06-18 14:32 UTC by T-Brex

**Alcuni commit sono del branch bre/issue302 perchè per sbaglio ho creato il branch bre/issue327 a partire da bre/issue302**

> * [x]  1. Inserire "vai al player video youtube" dopo ogni modalità e rendere visibile solo quello della modalità che è in riproduzione, come in beats
> * [x]  2. rimuovere i link e inserire la variabile data-link
> * [x]  3.  inserire descrizione iFrame per non vedenti: `aria-label="Player video youtube"` (ritengo che non sia necessario specificare ciò che è in riproduzione perchè è specificato dal title "Esempio _modalità_")

2024-06-18 17:51 UTC, LewentalDigital requested changes
Implementare i lang per le parole in inglese sui link "vai al player di youtube"

2024-06-19 17:43 UTC, LewentalDigital commented
- [ ] Invertire container iframe e container lista battle e mostrarli con l'ordine attuale via css
- [ ] Rimuovere tag strong da tutti i dt della lista
- [ ] Togliere il link vai al player dal dd e metterli fuori

2024-06-19 21:44 UTC, T-Brex commented
il terzo punto lo avevo già fatto nella issue dove aggiungo la descrizione ad ogni video dell'iframe

2024-06-20 07:27 UTC, LewentalDigital commented on template/modalita.html
> +					<strong aria-hidden="true"><sup>3</sup>/<sub>4</sub></strong
```suggestion
					<span aria-hidden="true"><sup>3</sup>/<sub>4</sub></span
```

2024-06-20 07:27 UTC, LewentalDigital commented on template/modalita.html
> +					tempo dei <strong aria-hidden="true"><sup>3</sup>/<sub>4</sub></strong
```suggestion
					tempo dei <span aria-hidden="true"><sup>3</sup>/<sub>4</sub></span
```

2024-06-20 07:29 UTC, LewentalDigital approved these changes

2024-06-20 07:29 UTC, merged