ho solo aggiunto uno span lang='en'
Gruppo-TecWeb/Codice pull request #339
Opened 2024-06-18 21:37 UTC by T-Brex

2024-06-19 08:36 UTC, LewentalDigital commented
Qui io ho un dubbio: TecWeb sta per Tecnologie Web, che è in italiano, noi lo pronunciamo in italiano?
Boh, chiederei consiglio degli altri
E magari al posto di Gruppo TecWeb potremmo chiamarci in un altro modo? 
@rzaupa @abenetazzo

2024-06-19 08:52 UTC, T-Brex commented
Forse dovremmo mettere un "abbr" o qualcosa del genere?

comunque a me tecWeb con Web inteso come ragnatela piaceva molto, però voglio sapere che ne pensano gli altri

2024-06-19 14:58 UTC, abenetazzo commented
Per me si può lasciare TecWeb, con attributo lang=en direi, no abbr che in questo caso non centra (non si tratta di un'abbreviazione del corso della Gaggi ma del nome del nostro gruppo)

2024-06-19 15:53 UTC, rzaupa commented
Non mi piace , "(link esterno)" è molto brutto , https://web.math.unipd.it/accessibility/test.html è una best practice, per instagram credo sia chiaro che sia un link esterno, per github forse basta scrivere "github" ?

2024-06-19 17:21 UTC, rzaupa requested changes
Inaccettabile, metti il riferimento ai link esterno come deciso dal vivo

2024-06-20 07:31 UTC, LewentalDigital commented on template/template-pagina.html
> +                <p>Prodotto da: <a href="https://github.com/Gruppo-TecWeb">Antonio Benetazzo, Alessando Bressan, Sebastiano Lewental, Riccardo Zaupa(link esterno).</a></p>
```suggestion
                <p>Prodotto da: <a href="https://github.com/Gruppo-TecWeb">Antonio Benetazzo, Alessando Bressan, Sebastiano Lewental, Riccardo Zaupa(link esterno)</a>.</p>
```

2024-06-20 11:49 UTC, rzaupa approved these changes

2024-06-20 11:49 UTC, merged